### ISSUE TITLE
Update to @azure/identity 4.*

### ISSUE THREAD

**Issue by AndreasHauber** [sschwinn-fdot/multer-atazure-storage-blob#1]
Hey @sschwinn-fdot ,

would you mind to update the dependency @azure/identity to 4.*. to get rid of some vulnerabilities? I have tested it localy and it seems not to break anything. Since it is only npm audit fix --force I have not created a pull request.

Best regards, 

Andreas

**Comment by sschwinn-fdot** [comment]
Done.

Note that this upgrade to the @azure/identity package may make it incompatible with projects that use typescript versions lower than 4.5.
